# Generated by Django 3.2.2 on 2021-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationchoices',
            name='choice',
            field=models.CharField(choices=[('Healthcare and Medicines', (('Hospital', 'Hospital'), ('Medicine', 'Medicine'))), ('Industrial and Agri', (('Farming', 'Farming'), ('Fishing', 'Fishing')))], max_length=200, unique=True),
        ),
    ]
