# Generated by Django 3.2.2 on 2021-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_locationchoices_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto/'),
        ),
    ]
