# Generated by Django 3.2.2 on 2021-06-03 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='IkigaiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ikigais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ikigaicategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserIkigai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai2_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai2_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H I 1 +', to='account.ikigais')),
                ('hobby_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H I 2 +', to='account.ikigais')),
                ('hobby_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H I 3 +', to='account.ikigais')),
                ('hobby_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H I 4 +', to='account.ikigais')),
                ('hobby_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H I 5 +', to='account.ikigais')),
                ('interest_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I I 1 +', to='account.ikigais')),
                ('interest_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I I 2 +', to='account.ikigais')),
                ('interest_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I I 3 +', to='account.ikigais')),
                ('interest_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I I 4 +', to='account.ikigais')),
                ('interest_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I I 5 +', to='account.ikigais')),
                ('professsion_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P I 1 +', to='account.ikigais')),
                ('professsion_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P I 2 +', to='account.ikigais')),
                ('professsion_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P I 3 +', to='account.ikigais')),
                ('professsion_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P I 4 +', to='account.ikigais')),
                ('professsion_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P I 5 +', to='account.ikigais')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
