# Generated by Django 3.2.2 on 2021-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_skillsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsets',
            name='professsion',
        ),
        migrations.AddField(
            model_name='skillsets',
            name='profession',
            field=models.IntegerField(default=0),
        ),
    ]
