# Generated by Django 3.2.2 on 2021-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210605_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilephoto/'),
        ),
    ]
