# Generated by Django 3.2.2 on 2021-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coveriamge',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
