# Generated by Django 3.2.2 on 2021-05-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_post_coveriamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coveriamge',
            new_name='coverimage',
        ),
    ]
