# Generated by Django 3.2.2 on 2021-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
