# Generated by Django 3.2.2 on 2021-05-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_auto_20210519_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_header', to='contents.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='trailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_trailing', to='contents.post'),
        ),
    ]
