# Generated by Django 3.2.2 on 2021-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_auto_20210519_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='coverimage/'),
        ),
    ]
