# Generated by Django 3.2.2 on 2021-05-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_course_courseordering_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
