# Generated by Django 3.2.2 on 2021-05-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseordering',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.course'),
        ),
    ]
