# Generated by Django 3.2.2 on 2021-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseimage',
            field=models.ImageField(blank=True, upload_to='courseimage/'),
        ),
    ]
