# Generated by Django 3.2.2 on 2021-06-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_ikigaicategory_ikigais_userikigai'),
        ('contents', '0022_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIkigai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('profession_ikigai2_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('interest_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai1_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai2_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai3_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai4_value', models.IntegerField(default=0, null=True)),
                ('hobby_ikigai5_value', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.course')),
                ('hobby_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 1 +', to='account.ikigais')),
                ('hobby_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 2 +', to='account.ikigais')),
                ('hobby_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 3 +', to='account.ikigais')),
                ('hobby_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 4 +', to='account.ikigais')),
                ('hobby_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 5 +', to='account.ikigais')),
                ('interest_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 1 +', to='account.ikigais')),
                ('interest_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 2 +', to='account.ikigais')),
                ('interest_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 3 +', to='account.ikigais')),
                ('interest_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 4 +', to='account.ikigais')),
                ('interest_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 5 +', to='account.ikigais')),
                ('professsion_ikigai1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 1 +', to='account.ikigais')),
                ('professsion_ikigai2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 2 +', to='account.ikigais')),
                ('professsion_ikigai3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 3 +', to='account.ikigais')),
                ('professsion_ikigai4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 4 +', to='account.ikigais')),
                ('professsion_ikigai5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 5 +', to='account.ikigais')),
            ],
        ),
    ]
