# Generated by Django 3.2.2 on 2021-06-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210603_1030'),
        ('contents', '0023_courseikigai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseikigai',
            name='hobby_ikigai1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 1 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='hobby_ikigai2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 2 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='hobby_ikigai3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 3 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='hobby_ikigai4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 4 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='hobby_ikigai5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='H C 5 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='interest_ikigai1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 1 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='interest_ikigai2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 2 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='interest_ikigai3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 3 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='interest_ikigai4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 4 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='interest_ikigai5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='I C 5 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='professsion_ikigai1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 1 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='professsion_ikigai2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 2 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='professsion_ikigai3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 3 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='professsion_ikigai4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 4 +', to='account.ikigais'),
        ),
        migrations.AlterField(
            model_name='courseikigai',
            name='professsion_ikigai5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P C 5 +', to='account.ikigais'),
        ),
    ]
