# Generated by Django 3.2.2 on 2021-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0024_auto_20210603_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseikigai',
            name='interst_ikigai2_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
