# Generated by Django 3.2.2 on 2021-06-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_courseikigai_interst_ikigai2_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_listing', models.TextField(blank=True)),
                ('usercourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.usercourse')),
            ],
        ),
    ]
