# Generated by Django 3.2.2 on 2021-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0026_usercourseactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='progress',
            field=models.FloatField(default=0, null=True),
        ),
    ]
