# Generated by Django 3.2.2 on 2021-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_usercourse_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(default='/assets/images/favpih.svg', upload_to='coverimage'),
        ),
    ]
