# Generated by Django 3.2.2 on 2021-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0028_alter_post_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(blank=True, default='/assets/images/favpih.svg', null=True, upload_to='coverimage'),
        ),
    ]
