# Generated by Django 3.2.2 on 2021-06-05 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0030_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.course'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
